version: '3.8'
services:
  db:
    image: postgres:alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=DVS
      - POSTGRES_PASSWORD=DVS@2022
      - POSTGRES_DB=DVS
    ports:
      - '5432:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local


